/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jgranados.ipc1_01_2023.swing;

import com.jgranados.ipc1_01_2023.exceptions.TableroExcepcion;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ActionEvent;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.plaf.OptionPaneUI;

/**
 *
 * @author jose
 */
public class MiFrame extends javax.swing.JFrame {

    public static final String BOMBA_1 = "/recursos/imgs/b1.jpeg";
    JButton otroBoton = new JButton();
    private BackendLabels backend;
    private MiCasilla[] casillas;

    /**
     * Creates new form MiFrame
     */
    public MiFrame() {
        backend = new BackendLabels();
        setPreferredSize(new Dimension(300, 300));
        JButton unBoton = new JButton();
        unBoton.setText("Un boton");
        unBoton.setSize(100, 25);
        unBoton.setLocation(0, 0);

        unBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accion(evt);
            }
        });

        otroBoton.setText("Otro boton");
        otroBoton.setSize(100, 25);
        otroBoton.setLocation(0, 35);
        add(otroBoton);

        add(unBoton);
        add(otroBoton);

        otroBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarEtiquetas();
            }
        });
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numeroEtiquetasTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        numeroEtiquetasTxt.setPreferredSize(new java.awt.Dimension(50, 35));
        getContentPane().add(numeroEtiquetasTxt);
        numeroEtiquetasTxt.setBounds(175, 5, 50, 35);

        jButton1.setText("pintar verde");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(240, 10, 140, 28);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // AQUI
        for (MiCasilla casilla : casillas) {
            casilla.setForeground(Color.GREEN);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MiFrame frame = new MiFrame();
                frame.setVisible(true);

            }
        });
    }

    private void accion(ActionEvent evt) {
        System.out.println("Hola");
        ImageIcon image = new ImageIcon(getClass().getResource(BOMBA_1));
        otroBoton.setIcon(image);
    }

    private void agregarEtiquetas() {
        /*String valor = numeroEtiquetasTxt.getText();
        try {
        
            Integer valorInt = Integer.valueOf(valor);
            for (int i = 0; i < valorInt; i++) {
                MiCasilla unaLabel = new MiCasilla("etiqueta No. " + (i + 1));
                unaLabel.setSize(50, 50);

                this.add(unaLabel);
                unaLabel.setLocation(0, (i * 50) + 100);

            }
            revalidate();
            repaint();
            pack();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El numero de eetiquetas no es correcto");
        }*/
        try {
            casillas = backend.generarCasillas(numeroEtiquetasTxt.getText());
            for (MiCasilla casilla : casillas) {
                this.add(casilla);
            }
            revalidate();
            repaint();
            pack();
        } catch (TableroExcepcion e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            /*MiCasilla[] casillas = backend.generarCasillas(1);
            for (MiCasilla casilla : casillas) {
                this.add(casilla);
            }
            revalidate();
            repaint();
            pack();*/
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField numeroEtiquetasTxt;
    // End of variables declaration//GEN-END:variables
}
